services:
  task-management-db:
    container_name: task-management-db
    image: postgres:17.2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./docker/initdb:/docker-entrypoint-initdb.d
      - task-management-db-data:/var/lib/postgresql/data
    ports:
      - "15432:5432"
    restart: unless-stopped
  task-management-app:
    container_name: task-management-app
    image: client:0.0.1
    build:
      context: .
      dockerfile: /docker/spring-boot/Dockerfile
    environment:
      SPRING_CONFIG_LOCATION: /config/application.yml
    volumes:
      - ./src/main/resources/application.yml:/config/application.yml
      - ./:/app
      - maven-repository-data:/root/.m2/repository
    depends_on:
      - task-management-db
    ports:
      - "9000:9000"
volumes:
  task-management-db-data:
  maven-repository-data: