spring:
  application:
    name: task-management-api
  datasource:
    url: jdbc:postgresql://task-management-db/task_management
    username: postgres
    password: secret
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    clean-disabled: false
server:
  port: 9000
  error:
    include-message: always
  servlet:
    context-path: /api/v1
jwt:
  secret: 3f4b2a7e8f1c3d2a0b5e6c8f2087a4d9c6e5f0bcb16a14f22986f4084e6c6a2d
  duration: 1d
springdoc:
  swagger-ui:
    path: /swagger-ui
  api-docs:
    path: /api-docs
  default-produces-media-type: application/json